apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-tls-cert
  namespace: ecommerce-backend-ns
spec:
  secretName: backend-ecommerce-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - authen.ndiliatalents.com