---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce-backend-ns
data:
  # AWS Configuration
  USE_AWS_SECRETS: "True"
  AWS_SECRET_NAME: "ecommerce2"
  AWS_REGION: "us-east-1"

  # Django Configuration
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  APPEND_SLASH: "False"

  # JWT Configuration
  JWT_ACCESS_TOKEN_LIFETIME: "60"
  JWT_REFRESH_TOKEN_LIFETIME: "1440"

  # Database Migration Settings
  RUN_MIGRATIONS: "true"
  COLLECT_STATIC: "true"
