name: CI/CD Pipeline to AWS
on:
  push:
    branches:
      - main
     
  # pull_request:
  #   branches:
  #     - main
      
    paths-ignore:
      - 'README.md'
    
env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: dev-${{ github.run_number }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  DEPLOYMENT_NAME: ecommerce-backend
  NAMESPACE: ecommerce-backend-ns
  SECRET_KEY: ${{ secrets.SECRET_KEY }}


jobs:
  aws_login_build_push:
    name: Checkout to github build and push to ecr
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Log in to Amazon ECR
      #   if: github.event_name != 'pull_request'
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

      # - name: Build and push Docker image
      #   if: github.event_name != 'pull_request'
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #   run: |
      #     docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
      #     docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      #     echo "image=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # - name: Update deployment file with new image
      #   if: github.event_name != 'pull_request'
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #   run: |
      #     # Update the image in deployment.yaml
      #     sed -i "s|image: .*|image: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG|g" deployment/deployment.yaml
      #     # Show the change
      #     echo "Updated deployment.yaml with new image:"
      #     grep "image:" deployment/deployment.yaml
      # - name: Commit and push updated deployment file
      #   if: github.event_name != 'pull_request'
      #   run: |
      #     git config --global user.name "chriscrsov"
      #     git config --global user.email "chriscrsov@gmail.com"
      #     git add deployment/deployment.yaml
      #     git commit -m "Update deployment image to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
      #     git push

      - name: Clone ArgoCD repository
        uses: actions/checkout@v3
        with:
          repository: NineTalents-Agency/backend_deployment
          token: ${{ secrets.CHECKOUT_TOKEN }}  
          path: deployment
          

      - name: Update ArgoCD deployment.yml
        env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          sed -i "s|image: .*|image: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG|g" deployment/deployment/deployment.yaml
      - name: Commit and push changes to ArgoCD repo
        run: |
          git config --global user.name "chriscrsov"
          git config --global user.email "chriscrsov@gmail.com"
          git add deployment/deployment/deployment.yaml
          git commit -m "core: update deployment image to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
          git push